language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jannyman/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jannyman/react-test npm test

after_success:
  - docker build -t jannyman/multi-client ./client
  - docker build -t jannyman/multi-nginx ./nginx
  - docker build -t jannyman/multi-server ./server
  - docker build -t jannyman/multi-worker ./worker
# Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to Docker Hub
  - docker push jannyman/multi-client
  - docker push jannyman/multi-nginx
  - docker push jannyman/multi-server
  - docker push jannyman/multi-worker
